---
# Common packages and configurations.
- name: ensure curl is at the latest version
  apt: name=curl state=latest
  tags: applications

- name: ensure git is at the latest version
  apt: name=git state=latest
  tags: applications

- name: ensure tmux is at the latest version
  apt: name=tmux state=latest
  tags: applications

- name: ensure vim is at the latest version
  apt: name=vim state=latest
  tags: applications

# Configure the firewall
- name: ensure ufw is at the latest version
  apt: name=ufw state=latest
  tags: firewall

- name: configure ufw
  ufw: state=enabled policy=deny logging=off
  tags: firewall

- name: allow ssh connections with ufw
  ufw: rule=allow name=OpenSSH
  tags: firewall
  
- name: allow ntp connections
  ufw: rule=allow port=123 proto=udp

# Configure ntp
- name: ensure ntp is at the latest version 
  apt: name=ntp state=present

- name: ensure the /etc/ntp.conf file exists
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: start the ntpd process
  service: name=ntp state=started enabled=yes

# Add groups
- name: create the sshusers group
  group: name=sshusers state=present

# Add users
- name: add zach user
  user: name=zach groups=sudo,sshusers
