---
# Common packages and configurations.
- name: ensure curl is at the latest version
  apt: name=curl state=latest

- name: ensure git is at the latest version
  apt: name=git state=latest

- name: ensure tmux is at the latest version
  apt: name=tmux state=latest

- name: ensure vim is at the latest version
  apt: name=vim state=latest

- name: ensure ufw is at the latest version
  apt: name=ufw state=latest
  tags: firewall

- name: configure ufw
  ufw: state=enabled policy=deny
  tags: firewall

- name: allow ssh connections with ufw
  ufw: rule=allow name=OpenSSH
  tags: firewall

# Configure ntp
- name: ensure ntp is at the latest version 
  apt: name=ntp state=present

- name: ensure the /etc/ntp.conf file exists
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: start the ntpd process
  service: name=ntp state=started enabled=yes
