---
# Common packages and configurations.
- name: ensure curl is at the latest version
  apt: name=curl state=latest

- name: ensure git is at the latest version
  apt: name=git state=latest

- name: ensure tmux is at the latest version
  apt: name=tmux state=latest

- name: ensure vim is at the latest version
  apt: name=vim state=latest
